package cube.model.face;

// Basic symmetries of the cube. All 48 cube symmetries can be generated by sequences of these 4 symmetries.
public enum BasicSymmetry {
    ROT_URF3,
    ROT_F2,
    ROT_U4,
    MIRR_LR2;

    public static final int COUNT = 4;

    public static BasicSymmetry fromIndex(int index) {
        return values()[index];
    }
}
